name: background_downloader
description: A multi-platform background file downloader and uploader. Define the task, enqueue and monitor progress

version: 8.9.4
repository: https://github.com/781flyingdutchman/background_downloader
  
# Modified environment constraints
environment:
  sdk: ">=2.19.0 <3.5.0"  # Lowered SDK constraint
  flutter: ">=3.0.0"      # Lowered Flutter constraint

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.0
  http: ^0.13.0          # Using older http version
  path_provider: ^2.0.2  # This can stay as is
  path: ^1.8.0
  async: ^2.6.0         # This can stay as is
  mime: ^1.0.0          # Downgraded
  collection: ^1.15.0   # This can stay as is

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Downgraded
  mockito: ^5.0.17      # This can stay as is
  build_runner: ^2.3.0  # Downgraded

platforms:
  android:
  ios:
  linux:
  macos:
  windows:


flutter:
  plugin:
    platforms:
      android:
        package: com.bbflight.background_downloader
        pluginClass: BDPlugin
      ios:
        pluginClass: BackgroundDownloaderPlugin
